# Generated by Django 3.2.6 on 2021-09-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vani', '0002_prabhu_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='prabhu',
            name='description',
            field=models.TextField(default='Description goes here', max_length=9000),
            preserve_default=False,
        ),
    ]
