# Generated by Django 3.2.6 on 2021-09-01 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vani', '0004_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.CharField(max_length=900000),
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=100)),
                ('song', models.FileField(upload_to='songs/')),
                ('prabhu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vani.prabhu')),
            ],
        ),
    ]
