# Generated by Django 3.2.6 on 2021-09-01 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vani', '0005_auto_20210901_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='prabhu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vani.content'),
        ),
    ]
