# Generated by Django 3.2.6 on 2021-09-02 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vani', '0006_alter_audio_prabhu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='song_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vani.audio'),
        ),
    ]
