# Generated by Django 3.2.6 on 2021-09-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vani', '0007_alter_playlist_song_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=900)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=10000)),
                ('live_link', models.CharField(max_length=9000)),
            ],
        ),
    ]
