# Generated by Django 3.2.6 on 2021-09-02 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vani', '0008_notifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
    ]
