# Generated by Django 3.2.6 on 2021-09-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vani', '0009_rename_notifications_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='(no subject)', max_length=900)),
                ('rating_content', models.TextField(max_length=9000)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='live_link',
            field=models.CharField(blank=True, max_length=9000),
        ),
    ]
